### ISSUE TITLE
IllegalArgumentException , android 11

### ISSUE THREAD

**Issue by j2emanue** [elevenetc/TextSurface#20]
java.lang.IllegalArgumentException: Invalid Region.Op - only INTERSECT and DIFFERENCE are allowed
        at android.graphics.Canvas.checkValidClipOp(Canvas.java:853)
        at android.graphics.Canvas.clipRect(Canvas.java:992)
        at su.levenetc.android.textsurface.animations.Slide.apply(Slide.java:157)
        at su.levenetc.android.textsurface.Text.onDraw(Text.java:112)
        at su.levenetc.android.textsurface.TextSurface.onDraw(TextSurface.java:88)
        at android.view.View.draw(View.java:22350)
        at android.view.View.updateDisplayListIfDirty(View.java:21226)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4500)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4473)
        at android.view.View.updateDisplayListIfDirty(View.java:21186)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4500)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4473)
        at android.view.View.updateDisplayListIfDirty(View.java:21186)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4500)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4473)
        at android.view.View.updateDisplayListIfDirty(View.java:21186)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4500)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4473)
        at android.view.View.updateDisplayListIfDirty(View.java:21186)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4500)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4473)

i think the fix for this could be here: https://stackoverflow.com/q/52922866/835883

can you see how can help resolve this ?  on older device not seeing the issue.

**Comment by sharukh967** [comment]
I am facing this issue too. @elevenetc

**Comment by masterQian** [comment]
各位，android studio 3.6.0 已修复，但是作者之前更新的jar包字节码无法修改，如果现在导入仍然会出现错误。只需要手动将作者源代码拷贝到android studio中加入项目共同编译或者手动打jar包，就可以正常运行了。
